from transformers import CLIPModel, CLIPProcessor, CLIPVisionModel
from typing import List, Optional
from tqdm import tqdm
import torch



def load_model(model_name: str, ft_vision_name: str = None):
    """
    Load a CLIP model and optionally replace its vision encoder with fine-tuned weights.

    Args:
        model_name (str): The name or path of the pretrained CLIP model to load.
        ft_vision_name (str, optional): The name or path of a fine-tuned vision encoder
                                        to replace the default vision model. Defaults to None.

    Returns:
        CLIPModel: The loaded CLIP model, possibly with a fine-tuned vision encoder.
        CLIPProcessor: The corresponding CLIP processor.
    """

    # Load the base CLIP model (both vision and text encoders) and its processor
    model = CLIPModel.from_pretrained(model_name)
    processor = CLIPProcessor.from_pretrained(model_name)

    # If a fine-tuned vision encoder is provided, load its weights
    if ft_vision_name:
        # Load the fine-tuned vision encoder
        vision_model = CLIPVisionModel.from_pretrained(ft_vision_name)

        # Replace the vision encoder weights in the base model with the fine-tuned ones
        model.vision_model.load_state_dict(vision_model.vision_model.state_dict())

    return model, processor



def generate_text_embeddings(labels_list_per_task: list, templates_list_per_task: list, processor: CLIPProcessor, model, device: str = "cpu"):
    """
    Generate normalized text embeddings for labels combined with prompt templates.

    Args:
        labels_list_per_task (list): A list of label lists, one list per task.
                                     Example: [["cat", "dog"], ["car", "bike"]]
        templates_list_per_task (list): A list of template functions (per task).
                                        Each template is a function that formats a label.
                                        Example: [["a photo of a {}", "a drawing of a {}"], ...]
        processor (CLIPProcessor): HuggingFace CLIP processor for text preprocessing.
        model: CLIP model with a `get_text_features` method (e.g., CLIPModel from HuggingFace).
        device (str, optional): Device to run on ("cpu" or "cuda"). Defaults to "cpu".

    Returns:
        text_embeds (torch.Tensor): Normalized embeddings of all labelXtemplate combinations.
        label_per_template (list): A flat list of labels, one for each template-label combination.
        template_labels (list): The actual text strings generated (template applied to label).
        total_num_templates (int): The total number of templates across all tasks.
    """

    # Will store all sentences generated by applying templates to labels
    template_labels = []

    # Will store the corresponding raw labels for each generated sentence
    label_per_template = []

    # Count the total number of templates across all tasks (sublists)
    total_num_templates = sum(len(sublist) for sublist in templates_list_per_task)

    # Generate all template-based sentences for each label
    # Example: label="cat", template="a photo of a {}" -> "a photo of a cat"
    for label_names, task_template in zip(labels_list_per_task, templates_list_per_task):
        for label in label_names:
            for template in task_template:
                template_labels.append(template(label))   # Save full sentence
                label_per_template.append(label)         # Save original label

    # Compute embeddings using CLIP, no gradient needed
    with torch.no_grad():
        # Preprocess text with the CLIP processor
        text_inputs = processor(
            text=template_labels,
            return_tensors="pt",
            padding=True
        ).to(device)

        # Extract text embeddings from the CLIP model
        text_embeds = model.get_text_features(**text_inputs)

        #### NEW EDIT 09/02/26 ####
        #text_embeds = text_embeds.pooler_output (#there is .pooler_output in Drive version)
        #### END OF NEW EDIT ####

        # Normalize embeddings to unit length (L2 norm = 1)
        text_embeds = text_embeds / text_embeds.norm(p=2, dim=-1, keepdim=True)

    # Return embeddings and helper lists, lengths
    return text_embeds, label_per_template, template_labels, total_num_templates



def evaluate_model(model, dataloader, processor, text_embeds, labels_per_temp, labels_mapping, device: str = "cpu"):

    correct = 0
    total = 0

    for images, labels in tqdm(dataloader):
        inputs = processor(images=images, return_tensors="pt", padding=True).to(device)
        labels = labels.to(device)

        with torch.no_grad():
            image_embeds = model.get_image_features(**inputs)
            ## NEW EDIT 09/02/26 ##
            #image_embeds = image_embeds.pooler_output (# there is .pooler_output in Drive version)
            ## END OF NEW EDIT ##
            image_embeds = image_embeds / image_embeds.norm(p=2, dim=-1, keepdim=True)

            similarity = image_embeds @ text_embeds.T
            preds = similarity.argmax(dim=-1)
            real_preds = [labels_per_temp[idx] for idx in preds]
            real_preds = [labels_mapping[x] for x in real_preds]
        '''
        print(real_preds)
        print()
        print(labels)
        print()
        print(real_preds == labels)
        '''
        correct += (torch.Tensor(real_preds).to(device) == labels).sum().item()
        total += labels.size(0)

        accuracy = correct / total


    return accuracy